### ISSUE TITLE
Relative symlink  issue

### ISSUE THREAD

**Issue by mehdidc** [mlfoundations/open-diffusion#1]
Thanks @vramanuj for this really nice repo!

I started to experiment with it and had an issue with symlinks that are used to indicate the current pipeline folder.
In my case, the symlinks were dead because they are pointing to relative path, so resuming did not work.
Simply adding .absolute() to save_path in `https://github.com/mlfoundations/open-diffusion/blob/main/train.py#L311`
and `https://github.com/mlfoundations/open-diffusion/blob/main/train.py#L509` makes it work fine.

Or did you do anything else that made it work anyway?

**Comment by vkramanuj** [comment]
Hi Mehdi, I believe that fix should work. In my configs I used only absolute paths, so I didn’t come across this issue. You could also use .absolute().resolve() so your path ends up cleaner. Thanks for pointing this out! Feel free to submit a PR to this effect if you get the chance. Otherwise I can update the code later :-)

**Comment by mehdidc** [comment]
Thanks,  I see, sure will open a PR!

**Comment by vkramanuj** [comment]
Closed with #3
